name: 'setup_cache'
description: 'sets up the shared cache'
inputs:
  compiler:
    required: true
    type: string
  build_type:
    required: true
    type: string
  generator:
    required: true
    type: string


runs:
  using: "composite"
  steps:
    - name: Cache
      uses: actions/cache@v4
      with:
        # You might want to add .ccache to your cache configuration?
        path: |
          ~/.cache/pip
          ~/.ccache
          ~/vcpkg
          ${{ github.workspace }}/build/vcpkg_installed
          ${{ env.CONAN_USER_HOME }}
          ${{ env.HOME }}/.cache/vcpkg/archives
          ${{ env.XDG_CACHE_HOME }}/vcpkg/archives
          ${{ env.LOCALAPPDATA }}\vcpkg\archives
          ${{ env.APPDATA }}\vcpkg\archives
          ${{ github.workspace }}/build
          ~/.sonar/cache
          ~/.cache/ccache
          ~/.ccache
          ~/.config/ccache
          ~/Library/Caches/ccache
          ${{ env.LOCALAPPDATA }}/ccache
          ${{ env.XDG_CACHE_HOME }}/ccache
        key: ${{ runner.os }}-${{ inputs.compiler }}-${{ inputs.build_type }}-${{ inputs.generator }}-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.compiler }}-${{ inputs.build_type }}
